#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/home/pip/projects/primate-run/primate/packages/primate/lib/node_modules:/home/pip/projects/primate-run/primate/packages/primate/node_modules:/home/pip/projects/primate-run/primate/packages/node_modules:/home/pip/projects/primate-run/primate/node_modules:/home/pip/projects/primate-run/node_modules:/home/pip/projects/node_modules:/home/pip/node_modules:/home/node_modules:/node_modules:/home/pip/projects/primate-run/primate/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/home/pip/projects/primate-run/primate/packages/primate/lib/node_modules:/home/pip/projects/primate-run/primate/packages/primate/node_modules:/home/pip/projects/primate-run/primate/packages/node_modules:/home/pip/projects/primate-run/primate/node_modules:/home/pip/projects/primate-run/node_modules:/home/pip/projects/node_modules:/home/pip/node_modules:/home/node_modules:/node_modules:/home/pip/projects/primate-run/primate/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../primate/lib/bin.js" "$@"
else
  exec node  "$basedir/../primate/lib/bin.js" "$@"
fi
